// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzE41tXs6vxt9r5kgh46iOYAYt9emeac',
    appId: '1:1081906128156:web:a0132e81ca035eff2e46d9',
    messagingSenderId: '1081906128156',
    projectId: 'intersect-innovation-hub-task',
    authDomain: 'intersect-innovation-hub-task.firebaseapp.com',
    storageBucket: 'intersect-innovation-hub-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVRl-CtZ86YljniY_-h7ADL3LiVm6-E0',
    appId: '1:1081906128156:android:e66fd214a4150d392e46d9',
    messagingSenderId: '1081906128156',
    projectId: 'intersect-innovation-hub-task',
    storageBucket: 'intersect-innovation-hub-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzmaTOMXvAINe7LBNFxsd5myVlm3Ao-U',
    appId: '1:1081906128156:ios:0389d48c34989f0d2e46d9',
    messagingSenderId: '1081906128156',
    projectId: 'intersect-innovation-hub-task',
    storageBucket: 'intersect-innovation-hub-task.firebasestorage.app',
    iosBundleId: 'com.example.intersectInnovationHubTask',
  );
}
